name: test

on:
  push:
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Cargo.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: stable
      - uses: actions/cache@v3
        with:
          key: v1-${{ runner.os }}-${{ hashFiles('**/Cargo.lock') }}
          path: |
            target
            ~/.cargo
      - run: cargo check
