on:
  push:
    branches:
      - master
      - develop
      - feature/*
    paths:
      - 'src/**'
      - '.github/workflows/**'
      - 'Cargo.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v1
      - run: cargo check
